apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberag-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: 'Helm'
    meta.helm.sh/release-namespace: 'default'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Release.Name }}-secret
      containers:
      - name: kuberag
        image: inventivework/kuberag:0.0.18
        command: [ "/bin/sh", "-c", "env", "/etc/secret-volume"]
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-cm
        ports:
        - containerPort: 5000