apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: 'Helm'
    meta.helm.sh/release-namespace: 'default'