apiVersion: v1
kind: Service
metadata:
  name: kuberag-app-service
spec:
  selector:
    app: kuberag
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer  # Or NodePort, ClusterIP