apiVersion: v1
kind: Service
metadata:
  name: kuberag-app-service
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: 'Helm'
    meta.helm.sh/release-namespace: 'default'
spec:
  selector:
    app: kuberag
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer  # Or NodePort, ClusterIP